version: "3.7"
services:
  xpla:
    restart: unless-stopped
    container_name: xpla-validator
    image: ${IMAGE}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    command: xplad start
    network_mode: "host"
    volumes:
      - /mnt/data/xpla:/root/.xpla
      - /mnt/data/genesis:/root/.genesis
    ports:
      - "8545:8545"
      - "9090:9090"
      - "26656:26656"
      - "127.0.0.1:26657:26657"
      - "26658:26658"